### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Jaimss** [GeorgH93/PCGF_PluginLib#11]
Hey, I am trying to use the UUID converter, and I can't seem to get it to work. 
I added edited my pom.xml exactly as is mentioned [here](https://github.com/GeorgH93/PCGF_PluginLib/blob/master/README.md). I added the repo and dependencies, and edited the <plugin>. I fixed the shadedPattern part to have my package name (net.infinitycraft.bungeereport). Upon adding this to my plugin, however, I can't get it to load. 

Here is a startup log:
https://hastebin.com/felulijifa.md

Please help me get this working because it will be a life saver!

**Comment by GeorgH93** [comment]
Please use this shade configuration:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-shade-plugin</artifactId>
    <version>3.1.0</version>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>shade</goal>
            </goals>
            <configuration>
                <createDependencyReducedPom>false</createDependencyReducedPom>
                <minimizeJar>true</minimizeJar>
                <artifactSet>
                    <includes>
                        <include>at.pcgamingfreaks:PluginLib</include>
                    </includes>
                </artifactSet>
                <relocations>
                    <relocation>
                        <pattern>at.pcgamingfreaks</pattern>
                        <shadedPattern>your_package.libs.at.pcgamingfreaks</shadedPattern>
                    </relocation>
                </relocations>
                <filters>
                    <filter>
                        <artifact>at.pcgamingfreaks:PluginLib</artifact>
                        <excludes>
                            <exclude>*.yml</exclude>
                        </excludes>
                    </filter>
                </filters>
            </configuration>
        </execution>
    </executions>
</plugin>
```

This was an oversight on my side when adding the documentation.
BungeeCord tries to load the `bungee.yml` before the `plugin.yml` file to allow one jar for Bukkit and BugneeCord. The old shade configuration copied the `bungee.yml`, `plugin.yml`, `bungee_config.yml` and `config.yml` files which caused the problem.
I will update the description in the readme accordingly.

**Comment by Jaimss** [comment]
tysm!
