### ISSUE TITLE
PCGF_PluginLib doesn't load on my server

### ISSUE THREAD

**Issue by MaClarenRGS** [GeorgH93/PCGF_PluginLib#13]
I've downloaded marriagemaster to my server, but it need PCGF, i've already add PCGF_PluginLIB.jar to my server, but marriagemaster doesn't load, i have the following issue
![dsds](https://user-images.githubusercontent.com/67023331/84819564-d8e8f380-afdd-11ea-85b2-0b18cd794db2.PNG)

**Comment by GeorgH93** [comment]
Whats the log when the server tries to load the PCGF PluginLib?
Which Server version are you using?
