### ISSUE TITLE
Gradle ShadowJar Exclusion

### ISSUE THREAD

**Issue by Jaimss** [GeorgH93/PCGF_PluginLib#14]
Do you have an example of [this](https://github.com/GeorgH93/PCGF_PluginLib#shading-the-library-into-your-plugin-with-maven) for gradle?

I am trying to use `shadowJar`, but when I do `exclude('*.yml') `, it also excludes my plugin's `plugin.yml`. Do you know how I can exclude for only the plugin lib dependency?

**Comment by GeorgH93** [comment]
Sorry I have never used gradle.

If you use version `1.0.30-SNAPSHOT` of the library you can skip the exclusion of the yml files (I have excluded them from the jar in the repo). But please note that for now version 1.0.29 and 1.0.30 should not be minimized (will be resolved with 1.0.31, once I have completed splitting all the NMS dependent code from the Bukkit API code).

**Comment by Jaimss** [comment]
Ok thanks.
