### ISSUE TITLE
Username History API Removal Error

### ISSUE THREAD

**Issue by kotarobo** [GeorgH93/PCGF_PluginLib#39]
https://help.minecraft.net/hc/en-us/articles/8969841895693-Username-History-API-Removal-FAQ-

https://pastebin.com/AEMEsat3

I got the error I put on pastebin with the plugin that I have been using PGCF.
The author told me that it seems to be caused by the Minecraft API being removed.
I would appreciate it if you could change it so that the error does not occur.

**Comment by GeorgH93** [comment]
Should be fixed with [this build](https://ci.pcgamingfreaks.at/job/PluginLib/681/artifact/target/PCGF_PluginLib-1.0.38-SNAPSHOT.jar).

**Comment by kotarobo** [comment]
It worked! Thank you!
